// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "prisma/schema",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        /*
         * One URL for both the app and the migration engine.
         *
         * This used to be split: migrations ran through a DIRECT_DATABASE_URL
         * because Neon's `channel_binding=require` was something the `pg`
         * driver adapter could negotiate and Prisma's migration engine could
         * not. MySQL on the same host as the app has no such parameter — and
         * no TLS handshake to disagree about — so the split has nothing left
         * to work around.
         */
        url: process.env.DATABASE_URL,
    },
});
