-- Lets a CAMPAIGN collect money before the order ships, using the accounts the
-- shop already has. See openspec/changes/add-landing-page-advance-payment.
--
-- ONE BOOLEAN, DEFAULTING TO FALSE, and no backfill. Every existing campaign
-- reads as "does not ask", which is what it is — so this deploys under live
-- ad traffic without changing a single page.
--
-- NOTE WHAT IS ABSENT: there is no account column here, and there must never
-- be one. The bKash/Nagad/bank details stay on
-- StoreSetting.checkoutConfig.advancePayment, shared by every campaign,
-- because a merchant maintaining the same number in six campaign pages will
-- eventually update five of them — and the sixth takes real money to a closed
-- account, with nothing to detect it.
--
-- The switch is an AND, not an override: a campaign asks only when this is
-- true AND the shop has advance payment on with at least one account. So
-- clearing the shop's accounts degrades every campaign to cash on delivery
-- rather than leaving pages asking for money with nowhere to send it.
--
-- NOTE — the trigram index hazard (carried forward from
-- 20260916183105_add_hot_path_indexes, which is where the full account lives):
-- `Product_name_trgm_idx`, `Product_sku_trgm_idx` and `Brand_name_trgm_idx`
-- were raw-SQL indexes Prisma read as drift and emitted DROP INDEX for in every
-- generated migration. That migration declared them in Product.prisma and
-- Brand.prisma, so generated migrations should no longer try to drop them —
-- but CHECK EVERY GENERATED MIGRATION ANYWAY. Committing those drops silently
-- degrades ProductService.searchProducts to a sequential scan, and nothing
-- fails loudly when it happens. This file contains no DROP INDEX; the generated
-- output was checked and carried none.

-- AlterTable
ALTER TABLE "LandingPage" ADD COLUMN     "requiresAdvancePayment" BOOLEAN NOT NULL DEFAULT false;
