-- The storefront's floating chat bubble: { enabled, channel, whatsappNumber?,
-- messengerUsername?, greeting? }.
-- See openspec/changes/add-footer-credit-and-chat-widget, design.md D4 and D5.
--
-- Purely additive and nullable with NO BACKFILL. Null resolves to
-- DEFAULT_CHAT_WIDGET, which is DISABLED, so this migration puts no bubble on
-- any existing storefront the moment it applies and there is nothing to
-- reconcile.
--
-- The column is PUBLIC — `GET /settings/public` serves this whole row — and by
-- the rule `integrationConfig` states, it therefore holds no credential. A
-- phone number and a Messenger handle are already printed on the site; an
-- access token would not be, and belongs in IntegrationCredential.
--
-- A BLANK `whatsappNumber` is a meaningful value, not a placeholder: it means
-- "use the store's contactPhone", resolved on READ by `resolveChatWidget` in
-- store-setting.service.ts and never written back. Backfilling this column with
-- the contact phone would freeze today's number into every row and break that
-- link, which is why there is no backfill here and must not be one later.
--
-- Postgres constrains none of the above; `chatWidgetSchema` in
-- store-setting.validation.ts is the only gate, which is the standing
-- arrangement for every Json column on this table.
--
-- NOTE — the trigram index hazard (carried forward from
-- 20260916183105_add_hot_path_indexes, which is where the full account lives):
-- `Product_name_trgm_idx`, `Product_sku_trgm_idx` and `Brand_name_trgm_idx`
-- were raw-SQL indexes Prisma read as drift and emitted DROP INDEX for in every
-- generated migration. That migration declared them in Product.prisma and
-- Brand.prisma, so generated migrations should no longer try to drop them —
-- but CHECK EVERY GENERATED MIGRATION ANYWAY. Committing those drops silently
-- degrades ProductService.searchProducts to a sequential scan, and nothing
-- fails loudly when it happens. This one was generated with `--create-only`,
-- inspected, and carried none: it contains no DROP INDEX.

-- AlterTable
ALTER TABLE "StoreSetting" ADD COLUMN     "chatWidget" JSONB;
