-- Drops a landing page's own delivery price list. A campaign's delivery charge
-- now comes from the SHOP's delivery options, derived from the district and
-- area the shopper picks — the same resolution the shop's checkout uses.
-- See openspec/changes/add-landing-page-destination-picker.
--
-- THE AUTHORED PRICES ARE NOT MIGRATED INTO THE SHOP'S OPTIONS, and that is a
-- decision rather than an omission. A campaign charging 90 for ঢাকার আশেপাশে
-- where the shop charges 100 has TWO rates, and only the merchant knows which
-- is now correct. Copying one over the other would set a price nobody chose —
-- the same reasoning that keeps DEFAULT_DELIVERY_ZONES from seeding a made-up
-- rate. The shop's options are the single price list from here on; a merchant
-- who needs a campaign-specific rate adds a delivery option for it in Checkout
-- Setting, where every other price already lives.
--
-- SO SOME CAMPAIGNS CHANGE PRICE ON DEPLOY. That is the point of the change —
-- the two paths disagreed and one of them was not where the merchant looks —
-- but it is a live price change on live ads, and it belongs in the release note
-- rather than being discovered from an order.
--
-- WHAT IS LOST: the authored labels and prices on each page. Orders already
-- placed are untouched — they captured their zone label at placement, so past
-- history still reads as what that shopper actually chose.
--
-- WHAT THIS ALSO COSTS: a campaign can no longer sell while the shop has
-- configured no delivery at all. That used to work deliberately (see
-- add-single-product-landing-page design.md D3) and no longer does — a shop
-- with no delivery options cannot take campaign orders, exactly as it cannot
-- take catalogue ones.
--
-- NOTE — the trigram index hazard (carried forward from
-- 20260916183105_add_hot_path_indexes, which is where the full account lives):
-- `Product_name_trgm_idx`, `Product_sku_trgm_idx` and `Brand_name_trgm_idx`
-- were raw-SQL indexes Prisma read as drift and emitted DROP INDEX for in every
-- generated migration. That migration declared them in Product.prisma and
-- Brand.prisma, so generated migrations should no longer try to drop them —
-- but CHECK EVERY GENERATED MIGRATION ANYWAY. Committing those drops silently
-- degrades ProductService.searchProducts to a sequential scan, and nothing
-- fails loudly when it happens. This file contains no DROP INDEX; it was
-- written by hand and carries none.

-- AlterTable
ALTER TABLE "LandingPage" DROP COLUMN "deliveryZones";
