import { Router } from "express";
import { AnalyticsRoutes } from "../module/analytics/analytics.route";
import { AuditLogRoutes } from "../module/audit-log/audit-log.route";
import { AuthRoutes } from "../module/auth/auth.route";
import { BannerRoutes } from "../module/banner/banner.route";
import { BrandRoutes } from "../module/brand/brand.route";
import { CampaignRoutes } from "../module/campaign/campaign.route";
import { CartRoutes } from "../module/cart/cart.route";
import { CategoryRoutes } from "../module/category/category.route";
import { CartCouponRoutes, CouponRoutes } from "../module/coupon/coupon.route";
import { CustomerAddressRoutes, CustomerRoutes } from "../module/customer/customer.route";
import { NotificationRoutes } from "../module/notification/notification.route";
import { OrderRoutes } from "../module/order/order.route";
import { PageRoutes } from "../module/page/page.route";
import { PaymentRoutes } from "../module/payment/payment.route";
import { ProductRoutes } from "../module/product/product.route";
import { PurchaseOrderRoutes } from "../module/purchase-order/purchase-order.route";
import { RefundNestedRoutes, RefundRoutes } from "../module/refund/refund.route";
import { PermissionRoutes, RoleRoutes } from "../module/role/role.route";
import { ReturnNestedRoutes, ReturnRoutes } from "../module/return/return.route";
import { AttributeRoutes } from "../module/attribute/attribute.route";
import { BundleDealRoutes } from "../module/bundle-deal/bundle-deal.route";
import { CollectionRoutes } from "../module/collection/collection.route";
import { ShippingRuleRoutes } from "../module/shipping-rule/shipping-rule.route";
import { TagRoutes } from "../module/tag/tag.route";
import { TaxRuleRoutes } from "../module/tax-rule/tax-rule.route";
import { ProductViewNestedRoutes } from "../module/product-view/product-view.route";
import { ReviewNestedRoutes, ReviewRoutes } from "../module/review/review.route";
import { ShipmentRoutes } from "../module/shipment/shipment.route";
import { StockMovementRoutes, StockRoutes } from "../module/stock/stock.route";
import { StoreSettingRoutes } from "../module/store-setting/store-setting.route";
import { SupplierRoutes } from "../module/supplier/supplier.route";
import { SupportMessageRoutes, SupportTicketRoutes } from "../module/support-ticket/support-ticket.route";
import { UploadRoutes } from "../module/upload/upload.route";
import { UserRoutes } from "../module/user/user.route";
import { WarehouseRoutes } from "../module/warehouse/warehouse.route";
import { WishlistRoutes } from "../module/wishlist/wishlist.route";

const router = Router();

router.use("/auth", AuthRoutes);
router.use("/users", UserRoutes);
router.use("/categories", CategoryRoutes);
router.use("/brands", BrandRoutes);
router.use("/attributes", AttributeRoutes);
router.use("/tax-rules", TaxRuleRoutes);
router.use("/shipping-rules", ShippingRuleRoutes);
router.use("/collections", CollectionRoutes);
router.use("/bundle-deals", BundleDealRoutes);
router.use("/tags", TagRoutes);
router.use("/products/:id/reviews", ReviewNestedRoutes);
// Above `/products` for the same reason as reviews: the product router's
// `/:slug` would otherwise capture `:id/views` first.
router.use("/products/:id/views", ProductViewNestedRoutes);
router.use("/products", ProductRoutes);
router.use("/cart", CartCouponRoutes);
router.use("/cart", CartRoutes);
router.use("/wishlist", WishlistRoutes);
router.use("/customers/me/addresses", CustomerAddressRoutes);
// MUST stay below the "me" mount above: "/customers/:id" would otherwise capture
// the literal "me" segment and 404 every self-service address request.
router.use("/customers", CustomerRoutes);
router.use("/orders/:id/payments", PaymentRoutes);
router.use("/orders/:id/shipment", ShipmentRoutes);
router.use("/orders/:id/returns", ReturnNestedRoutes);
router.use("/orders/:id/refunds", RefundNestedRoutes);
router.use("/orders", OrderRoutes);
router.use("/returns", ReturnRoutes);
router.use("/refunds", RefundRoutes);
router.use("/reviews", ReviewRoutes);
router.use("/warehouses", WarehouseRoutes);
router.use("/stock-movements", StockMovementRoutes);
router.use("/stock", StockRoutes);
router.use("/suppliers", SupplierRoutes);
router.use("/purchase-orders", PurchaseOrderRoutes);
router.use("/coupons", CouponRoutes);
router.use("/campaigns", CampaignRoutes);
router.use("/banners", BannerRoutes);
router.use("/support-tickets/:id/messages", SupportMessageRoutes);
router.use("/support-tickets", SupportTicketRoutes);
router.use("/notifications", NotificationRoutes);
router.use("/pages", PageRoutes);
router.use("/settings", StoreSettingRoutes);
router.use("/roles", RoleRoutes);
router.use("/permissions", PermissionRoutes);
router.use("/audit-logs", AuditLogRoutes);
router.use("/analytics", AnalyticsRoutes);
router.use("/uploads", UploadRoutes);

export const IndexRoutes = router;
