-- Which sections a CAMPAIGN page is composed of, and in what order.
-- See openspec/changes/add-landing-page-section-builder, design.md D1.
--
-- Purely additive and nullable with NO BACKFILL. Null is not a placeholder —
-- it is the meaningful value "never configured", which the storefront resolves
-- to the default section order, i.e. exactly the campaign page that rendered
-- before this column existed. Every existing landing page therefore renders
-- identically the moment this applies, and there is nothing to reconcile.
--
-- AN EMPTY ARRAY IS A DIFFERENT VALUE from null and must stay that way: `[]`
-- means the merchant configured this page to show nothing. Backfilling this
-- column to `[]` would convert every existing campaign from "as it always was"
-- into "deliberately blank", which is why there is no backfill here and must
-- not be one later.
--
-- The value is an ORDERED array of { key, enabled } plus the CUSTOM-only
-- content fields. Postgres constrains none of that; `sectionConfigSchema` in
-- landing-page.validation.ts is the only gate, which is the standing
-- arrangement for every Json column on this table.
--
-- NOTE — the trigram index hazard (carried forward from
-- 20260916183105_add_hot_path_indexes, which is where the full account lives):
-- `Product_name_trgm_idx`, `Product_sku_trgm_idx` and `Brand_name_trgm_idx`
-- were raw-SQL indexes Prisma read as drift and emitted DROP INDEX for in every
-- generated migration. That migration declared them in Product.prisma and
-- Brand.prisma, so generated migrations should no longer try to drop them —
-- but CHECK EVERY GENERATED MIGRATION ANYWAY. Committing those drops silently
-- degrades ProductService.searchProducts to a sequential scan, and nothing
-- fails loudly when it happens. This one was generated with `--create-only`,
-- inspected, and carried none: it contains no DROP INDEX.

-- AlterTable
ALTER TABLE "LandingPage" ADD COLUMN     "sectionConfig" JSONB;
